FROM python:3.10

# Set the working directory to /app
WORKDIR /api_server

# Copy the current directory contents into the container at /app
COPY . /api_server

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
